# Função Estimadora

In [1]:
import numpy as np
import pandas as pd

def estimate_Q(S, x):
    # matriz de contagem 
    n = np.array([sum(all(x[n:n+2] == (i,j)) for n in range(len(x))) for j in S for i in S]).reshape(len(S), len(S)).T
    # p_ij = n_ij \ SUM(n_i)
    p = lambda i,j: n[i,j] / sum(n[i]) 
    return np.array([[p(i,j) for j in range(len(S))] for i in range(len(S))])
    

# CM 1 

In [2]:
S = {0,1}
x = np.array(pd.read_csv('CM_ex1', delimiter=' ').x)
estimate_Q(S, x)

array([[0.78411405, 0.21588595],
       [0.20825147, 0.79174853]])

# CM 2

In [3]:
S = {1, 2, 3}
x = np.array(pd.read_csv('CM_ex2', delimiter=' ').x)
estimate_Q(S, x)

array([[0.66891892, 0.33108108, 0.        ],
       [0.        , 0.58369099, 0.41630901],
       [0.2059448 , 0.        , 0.7940552 ]])

# CM 3

In [4]:
S = {1, 2, 3}
x = np.array(pd.read_csv('CM_ex3', delimiter=' ').x)
estimate_Q(S, x)

array([[0.1       , 0.415625  , 0.484375  ],
       [0.27777778, 0.1871345 , 0.53508772],
       [0.56804734, 0.42899408, 0.00295858]])

# CM 4

In [5]:
S={1,2,3,4,5,6}
x = np.array(pd.read_csv('CM_ex4', delimiter=' ').x)
estimate_Q(S, x)

array([[0.32484076, 0.61146497, 0.06369427, 0.        , 0.        ,
        0.        ],
       [0.5047619 , 0.3047619 , 0.        , 0.        , 0.        ,
        0.19047619],
       [0.        , 0.48387097, 0.        , 0.        , 0.51612903,
        0.        ],
       [0.        , 0.        , 0.11111111, 0.44973545, 0.43915344,
        0.        ],
       [0.        , 0.        , 0.        , 0.30563798, 0.58753709,
        0.10682493],
       [0.        , 0.47368421, 0.        , 0.        , 0.52631579,
        0.        ]])